[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[target.aarch64-apple-darwin]
rustflags = [
  # Nightly
  "-Zshare-generics=y",
  "-Zthreads=0",
]